max_cores: <# cores>
min_pep_len: 8    # minimum length of peptide for in-silico digestion
max_pep_len: 40   # maximum length of peptide for in-silico digestion

proteindb_fasta: <path to the fasta file without decoys (SD1)>
proteindb_fasta_stop: "data/ensembl_ref_haplo_contam_proteinDB_stop.fa"
proteindb_fasta_filtered: "data/ensembl_ref_haplo_contam_proteinDB_filtered.fa"
proteindb_fasta_stop_filtered: "data/ensembl_ref_haplo_contam_proteinDB_stop_filtered.fa"

merged_psm_list: <path to the table with PSMs (SD3)>

mzml_dir: <path to the directory of mzML files, converted from raw files given in https://www.ebi.ac.uk/pride/archive/projects/PXD010154>
predictions_dir: <path to the directory with MP2PIP result files>